# Generated by Django 2.1 on 2018-08-16 14:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import reference_books.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Дополнительные затраты',
                'verbose_name_plural': 'Дополнительные затраты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Agriculture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reference_books')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Агрокультура',
                'verbose_name_plural': 'Агрокультуры',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('iso_4217_letter_code', models.CharField(max_length=3, verbose_name='ISO 4217 символьный код')),
                ('iso_4217_numeric_code', models.PositiveSmallIntegerField(validators=[reference_books.models.iso_4217_numeric_code_validator], verbose_name='ISO 4217 цыфровой код')),
                ('short_symbol', models.CharField(blank=True, max_length=5, null=True, verbose_name='Символ')),
                ('is_main', models.BooleanField(default=False, verbose_name='Является основной')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='FarmingTechniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reference_books')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Самоходная техника',
                'verbose_name_plural': 'Самоходная техника',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='FarmingTechniquesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип самоходной техники',
                'verbose_name_plural': 'Типы самоходной техники',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Удобрение',
                'verbose_name_plural': 'Удобрения',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326, verbose_name='Полигон поля')),
                ('square', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True, verbose_name='Площадь')),
                ('rent_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Стоимость аренды')),
                ('rent_cost_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Currency', verbose_name='Валюта стоимости аренды')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Топливо',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reference_books')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('farming_techniques', models.ManyToManyField(to='reference_books.FarmingTechniques', verbose_name='Самоходная техника')),
            ],
            options={
                'verbose_name': 'Прицепной аггрегат',
                'verbose_name_plural': 'Прицепные аггрегаты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MachineryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип прицепных агрещатов',
                'verbose_name_plural': 'Типы прицепных агрещатов',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('website', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Произвадитель',
                'verbose_name_plural': 'Произвадители',
            },
        ),
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Средство защиты растений',
                'verbose_name_plural': 'Средства защиты растений',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('seeding_rate', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Норма высева')),
                ('agriculture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Agriculture', verbose_name='Агрокультура')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Manufacturer', verbose_name='Произвадитель')),
            ],
            options={
                'verbose_name': 'Семена',
                'verbose_name_plural': 'Семена',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, verbose_name='Краткое название')),
                ('long_name', models.CharField(max_length=20, verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ('long_name',),
            },
        ),
        migrations.CreateModel(
            name='WorkAndTechnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Расход топлива')),
                ('farming_techniques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.FarmingTechniques', verbose_name='Самоходная техника')),
                ('fuel_rate_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Unit', verbose_name='Ед. измерения расхода топлива')),
                ('machinery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Machinery', verbose_name='Прицепной аггрегат')),
            ],
            options={
                'verbose_name': 'Работа и техника',
                'verbose_name_plural': 'Работа и техника',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид работ',
                'verbose_name_plural': 'Виды работ',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='workandtechnique',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.WorkType', verbose_name='Вид работ'),
        ),
        migrations.AddField(
            model_name='seed',
            name='seeding_rate_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Unit', verbose_name='Ед. измерения'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.MachineryType'),
        ),
        migrations.AddField(
            model_name='field',
            name='rent_cost_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_cost_unit', to='reference_books.Unit', verbose_name='Ед. измерения стоимости аренды'),
        ),
        migrations.AddField(
            model_name='field',
            name='square_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Unit', verbose_name='Ед. измерения'),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='farmingtechniques',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.FarmingTechniquesType'),
        ),
    ]
