# Generated by Django 2.1 on 2018-08-15 15:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reference_books')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Агрокультура',
                'verbose_name_plural': 'Агрокультуры',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326, verbose_name='Полигон поля')),
                ('square', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True, verbose_name='Площадь')),
                ('rent_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Стоимость аренды')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('website', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Произвадитель',
                'verbose_name_plural': 'Произвадители',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('seeding_rate', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Норма высева')),
                ('agriculture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Agriculture', verbose_name='Агрокультура')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Manufacturer', verbose_name='Произвадитель')),
            ],
            options={
                'verbose_name': 'Семена',
                'verbose_name_plural': 'Семена',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, verbose_name='Краткое название')),
                ('long_name', models.CharField(max_length=20, verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.AddField(
            model_name='seed',
            name='seeding_rate_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Unit', verbose_name='Ед. измерения'),
        ),
        migrations.AddField(
            model_name='field',
            name='square_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Unit', verbose_name='Ед. измерения'),
        ),
    ]
