# Generated by Django 2.1 on 2018-08-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='square_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Unit', verbose_name='Ед. измерения'),
        ),
    ]
