# Generated by Django 2.1 on 2018-08-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0002_processcycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processcycle',
            options={'ordering': ('sort',), 'verbose_name': 'Технологический цикл', 'verbose_name_plural': 'Технологические циклы'},
        ),
        migrations.AddField(
            model_name='processcycle',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Сортировка'),
        ),
    ]
