# Generated by Django 2.1 on 2018-08-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0003_auto_20180816_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ('sort', 'title'), 'verbose_name': 'Вид работ', 'verbose_name_plural': 'Виды работ'},
        ),
        migrations.AddField(
            model_name='worktype',
            name='sort',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Сортировка'),
        ),
    ]
