# Generated by Django 2.1 on 2018-08-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0004_auto_20180816_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmingtechniques',
            options={'ordering': ('title',), 'verbose_name': 'Самоходная техника', 'verbose_name_plural': 'Самоходная техника'},
        ),
        migrations.AlterModelOptions(
            name='fuel',
            options={'ordering': ('title',), 'verbose_name': 'Топливо', 'verbose_name_plural': 'Топливо'},
        ),
        migrations.AlterModelOptions(
            name='machinery',
            options={'ordering': ('title',), 'verbose_name': 'Прицепной аггрегат', 'verbose_name_plural': 'Прицепные аггрегаты'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ('title',), 'verbose_name': 'Вид работ', 'verbose_name_plural': 'Виды работ'},
        ),
    ]
