# Generated by Django 2.1 on 2018-08-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0004_auto_20180816_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='units',
            field=models.ManyToManyField(to='reference_books.Unit', verbose_name='Ед. измерения'),
        ),
    ]
