# Generated by Django 2.1 on 2018-08-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0005_worktype_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='workandtechnique',
            name='coast_for_output_rate_driver',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Оплата за норму по тарифу - механизаторы'),
        ),
        migrations.AddField(
            model_name='workandtechnique',
            name='coast_for_output_rate_others',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Оплата за норму по тарифу - другие'),
        ),
        migrations.AddField(
            model_name='workandtechnique',
            name='coefficient_for_quality_driver',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Коэфициент за качество - механизаторы'),
        ),
        migrations.AddField(
            model_name='workandtechnique',
            name='coefficient_for_quality_others',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Коэфициент за качество - другие'),
        ),
        migrations.AddField(
            model_name='workandtechnique',
            name='composition_driver',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Состав аггрегата - механизаторы'),
        ),
        migrations.AddField(
            model_name='workandtechnique',
            name='composition_others',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Состав аггрегата - другие'),
        ),
        migrations.AddField(
            model_name='workandtechnique',
            name='output_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Норма выработки'),
        ),
    ]
