# Generated by Django 2.1 on 2018-08-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0006_auto_20180816_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Удобрение',
                'verbose_name_plural': 'Удобрения',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Средство защиты растений',
                'verbose_name_plural': 'Средства защиты растений',
                'ordering': ('title',),
            },
        ),
    ]
