# Generated by Django 2.1 on 2018-08-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0006_auto_20180823_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Цена')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Fuel', verbose_name='Топливо')),
            ],
            options={
                'verbose_name': 'Стоимость топлива',
                'verbose_name_plural': 'Стоимость топлива',
            },
        ),
    ]
