# Generated by Django 2.1 on 2018-08-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0007_fuelcoast'),
    ]

    operations = [
        migrations.AddField(
            model_name='workandtechnique',
            name='fuel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Fuel', verbose_name='Топливо'),
            preserve_default=False,
        ),
    ]
