# Generated by Django 2.1 on 2018-09-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0008_workandtechnique_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculture',
            name='work_type',
            field=models.ManyToManyField(to='reference_books.WorkType'),
        ),
    ]
