# Generated by Django 2.1 on 2018-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0009_agriculture_work_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agriculture',
            options={'ordering': ('id',), 'verbose_name': 'Агрокультура', 'verbose_name_plural': 'Агрокультуры'},
        ),
        migrations.AddField(
            model_name='workandtechnique',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения периода выполнения'),
        ),
        migrations.AddField(
            model_name='workandtechnique',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала периода выполнения'),
        ),
    ]
