# Generated by Django 2.1 on 2018-08-16 13:06

from django.db import migrations, models
import reference_books.models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0009_auto_20180816_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='currency',
            name='iso_4217_numeric_code',
            field=models.PositiveSmallIntegerField(validators=[reference_books.models.iso_4217_numeric_code_validator], verbose_name='ISO 4217 цыфровой код'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='short_symbol',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Символ'),
        ),
    ]
