# Generated by Django 2.1 on 2018-08-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0010_auto_20180816_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Общие затраты',
                'verbose_name_plural': 'Общие затраты',
                'ordering': ('title',),
            },
        ),
    ]
