# Generated by Django 2.1 on 2018-08-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0011_additionalexpenditure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalexpenditure',
            options={'ordering': ('title',), 'verbose_name': 'Дополнительные затраты', 'verbose_name_plural': 'Дополнительные затраты'},
        ),
    ]
